version: 3

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_third_dbt_model
    description: "An extended dbt model with additional features"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: category
        description: "The category of the item"
        tests:
          - not_null
          - accepted_values:
              values: ['A', 'B', 'C']
      - name: category_group
        description: "The group derived from the category"
        tests:
          - not_null
          - accepted_values:
              values: ['Group 1', 'Group 2', 'Group 3']
      - name: model_run_at
        description: "Timestamp when the model was run"
        tests:
          - not_null